Update webrtc script for iOS
arg use_xcode_clang doesn't exist use is_clang instead

remove enable_ios_bitcode=true because a compilation issue:
error: -mllvm is not supported with -fembed-bitcode