add /bigobj for windows builds
since Jenkins is reporting
Sync_test.cpp : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj